/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import sistematuristico.AccesoData.PasajeData;
import sistematuristico.Entidades.Pasaje;

import java.awt.Color;
import java.awt.Component;
import java.time.temporal.ChronoUnit;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicArrowButton;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import sistematuristico.AccesoData.AlojamientoData;
import sistematuristico.AccesoData.PaqueteData;
import sistematuristico.Entidades.Paquete;

/**
 *
 * @author crist
 */
public class ABMPaquete extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    PaqueteData paqueteData = new PaqueteData();
    AlojamientoData alojamientoData = new AlojamientoData();
    PasajeData pasajeData = new PasajeData();

    public ABMPaquete() {
        initComponents();
        spinnerColor();
        CrearTabla();
        CargarTabla();
        EnableBottonRecuperar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFull = new javax.swing.JPanel();
        jPanelHead = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JPanel();
        jlabel_exit = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jPanelNuevo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfDestino = new javax.swing.JTextField();
        jtfFechaSalida = new javax.swing.JTextField();
        jtfTransporte = new javax.swing.JTextField();
        jtfImporteTotal = new javax.swing.JTextField();
        jtfAlojamiento = new javax.swing.JTextField();
        jtfServicio = new javax.swing.JTextField();
        jtfFechaIngreso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfOrigen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfImportePersona = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        bajaButton = new javax.swing.JButton();
        jCheckBoxEliminados = new javax.swing.JCheckBox();
        recuperarButton = new javax.swing.JButton();

        jPanelFull.setBackground(new java.awt.Color(56, 63, 79));
        jPanelFull.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHead.setBackground(new java.awt.Color(56, 63, 79));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 237, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminar Paquetes");

        jSeparator1.setBackground(new java.awt.Color(235, 237, 255));

        jSeparator2.setBackground(new java.awt.Color(235, 237, 255));

        btnSalir.setBackground(new java.awt.Color(56, 63, 79));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });

        jlabel_exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlabel_exit.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_Exit_25px.png"))); // NOI18N

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlabel_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelHeadLayout = new javax.swing.GroupLayout(jPanelHead);
        jPanelHead.setLayout(jPanelHeadLayout);
        jPanelHeadLayout.setHorizontalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeadLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeadLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelHeadLayout.setVerticalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeadLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelFull.add(jPanelHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jPanelBody.setBackground(new java.awt.Color(56, 63, 79));
        jPanelBody.setPreferredSize(new java.awt.Dimension(1000, 540));

        jPanelNuevo.setBackground(new java.awt.Color(56, 63, 79));

        jPanel1.setBackground(new java.awt.Color(56, 63, 79));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 237, 255));
        jLabel2.setText("Importe total a pagar:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(235, 237, 255));
        jLabel3.setText("Destino:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 237, 255));
        jLabel4.setText("Fecha de ingreso                                 Fecha de salida:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(235, 237, 255));
        jLabel6.setText("Tipo de transporte:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(235, 237, 255));
        jLabel7.setText("Tipo de alojamiento:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(235, 237, 255));
        jLabel8.setText("Tipo de servicio:");

        jtfDestino.setEditable(false);
        jtfDestino.setBackground(new java.awt.Color(56, 63, 79));
        jtfDestino.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfDestino.setForeground(new java.awt.Color(235, 237, 255));
        jtfDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfDestino.setFocusable(false);

        jtfFechaSalida.setEditable(false);
        jtfFechaSalida.setBackground(new java.awt.Color(56, 63, 79));
        jtfFechaSalida.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfFechaSalida.setForeground(new java.awt.Color(235, 237, 255));
        jtfFechaSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfFechaSalida.setFocusable(false);

        jtfTransporte.setEditable(false);
        jtfTransporte.setBackground(new java.awt.Color(56, 63, 79));
        jtfTransporte.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfTransporte.setForeground(new java.awt.Color(235, 237, 255));
        jtfTransporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfTransporte.setFocusable(false);

        jtfImporteTotal.setEditable(false);
        jtfImporteTotal.setBackground(new java.awt.Color(56, 63, 79));
        jtfImporteTotal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfImporteTotal.setForeground(new java.awt.Color(235, 237, 255));
        jtfImporteTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfImporteTotal.setFocusable(false);

        jtfAlojamiento.setEditable(false);
        jtfAlojamiento.setBackground(new java.awt.Color(56, 63, 79));
        jtfAlojamiento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfAlojamiento.setForeground(new java.awt.Color(235, 237, 255));
        jtfAlojamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfAlojamiento.setFocusable(false);

        jtfServicio.setEditable(false);
        jtfServicio.setBackground(new java.awt.Color(56, 63, 79));
        jtfServicio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfServicio.setForeground(new java.awt.Color(235, 237, 255));
        jtfServicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfServicio.setFocusable(false);

        jtfFechaIngreso.setEditable(false);
        jtfFechaIngreso.setBackground(new java.awt.Color(56, 63, 79));
        jtfFechaIngreso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfFechaIngreso.setForeground(new java.awt.Color(235, 237, 255));
        jtfFechaIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfFechaIngreso.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(235, 237, 255));
        jLabel5.setText("Origen:");

        jtfOrigen.setEditable(false);
        jtfOrigen.setBackground(new java.awt.Color(56, 63, 79));
        jtfOrigen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfOrigen.setForeground(new java.awt.Color(235, 237, 255));
        jtfOrigen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfOrigen.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(235, 237, 255));
        jLabel9.setText("Importe por persona:");

        jtfImportePersona.setEditable(false);
        jtfImportePersona.setBackground(new java.awt.Color(56, 63, 79));
        jtfImportePersona.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfImportePersona.setForeground(new java.awt.Color(235, 237, 255));
        jtfImportePersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfImportePersona.setFocusable(false);

        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinner1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jtfOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jtfFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(jtfTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(109, 109, 109)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jtfServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfImportePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jtfImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jtfOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jtfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jtfTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfImportePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelNuevoLayout = new javax.swing.GroupLayout(jPanelNuevo);
        jPanelNuevo.setLayout(jPanelNuevoLayout);
        jPanelNuevoLayout.setHorizontalGroup(
            jPanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNuevoLayout.setVerticalGroup(
            jPanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNuevoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jScrollPane.setBackground(new java.awt.Color(56, 63, 79));
        jScrollPane.setForeground(new java.awt.Color(56, 63, 79));

        jTable.setBackground(new java.awt.Color(56, 63, 79));
        jTable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable.setForeground(new java.awt.Color(235, 237, 255));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id pasaje", "trasporte", "importe", "origen"
            }
        ));
        jTable.setFocusable(false);
        jTable.setGridColor(new java.awt.Color(47, 52, 67));
        jTable.setSelectionBackground(new java.awt.Color(83, 81, 251));
        jTable.setSelectionForeground(new java.awt.Color(235, 237, 255));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(jTable);

        bajaButton.setBackground(new java.awt.Color(47, 52, 67));
        bajaButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bajaButton.setForeground(new java.awt.Color(235, 237, 255));
        bajaButton.setText("Baja Pasaje");
        bajaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaButtonActionPerformed(evt);
            }
        });

        jCheckBoxEliminados.setBackground(new java.awt.Color(56, 63, 79));
        jCheckBoxEliminados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBoxEliminados.setForeground(new java.awt.Color(235, 237, 255));
        jCheckBoxEliminados.setText("Mostrar Eliminados");
        jCheckBoxEliminados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxEliminados.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jCheckBoxEliminados.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxEliminadosStateChanged(evt);
            }
        });

        recuperarButton.setBackground(new java.awt.Color(47, 52, 67));
        recuperarButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        recuperarButton.setForeground(new java.awt.Color(235, 237, 255));
        recuperarButton.setText("Recuperar Pasaje");
        recuperarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recuperarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBodyLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(bajaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(recuperarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBodyLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jCheckBoxEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bajaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recuperarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFull.add(jPanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1000, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFull, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bajaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaButtonActionPerformed
        EliminarDeTabla();
        CargarTabla();
    }//GEN-LAST:event_bajaButtonActionPerformed

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        this.dispose();
    }//GEN-LAST:event_btnSalirMousePressed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        SeleccionarFila();
    }//GEN-LAST:event_jTableMouseClicked

    private void jCheckBoxEliminadosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxEliminadosStateChanged
        CargarTabla();
        EnableBottonRecuperar();
    }//GEN-LAST:event_jCheckBoxEliminadosStateChanged

    private void recuperarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recuperarButtonActionPerformed
        RecuperarPaquete();
        CargarTabla();
    }//GEN-LAST:event_recuperarButtonActionPerformed
    // </editor-fold>
    // </editor-fold>  
    private void spinnerColor() {
        JComponent editor = jSpinner1.getEditor();
        int n = editor.getComponentCount();
        for (int i = 0; i < n; i++) {
            Component c = editor.getComponent(i);
            if (c instanceof JTextField) {
                c.setForeground(new Color(235, 237, 255));
                c.setBackground(new Color(56, 63, 79));
                ((JTextField) c).setEditable(false);
            }
            if (c instanceof BasicArrowButton) {                //intento de cambiar color del boton NO FUNCIONA
                JButton b = (JButton) c;
                b.setBackground(new Color(56, 63, 79));
                b.setForeground(new Color(56, 63, 79));
            }
        }
    }

    private void CrearTabla() {
        //tabla origen
        JTableHeader TblHeaderOrigen = jTable.getTableHeader();
        TblHeaderOrigen.setBackground(new Color(56, 63, 79));
        TblHeaderOrigen.setForeground(new Color(235, 237, 255));

        jScrollPane.getViewport().setBackground(new Color(56, 63, 79)); //fondo sin grilla de color
        modelo.addColumn("ID");
        modelo.addColumn("Origen");
        modelo.addColumn("Destino");
        modelo.addColumn("Alojamiento");
        modelo.addColumn("Personas");
        jTable.setModel(modelo);
        jTable.setEnabled(true);
        jTable.setRowSelectionAllowed(true);
        jTable.getColumnModel().getColumn(0).setPreferredWidth(27);
        jTable.getColumnModel().getColumn(4).setPreferredWidth(27);

    }

    private void CargarTabla() {
        borrarFilaDestino();
        if (paqueteData.listarPaquetes() != null) {
            for (Paquete paquete : paqueteData.listarPaquetes()) {
                if (!jCheckBoxEliminados.isSelected() ? paquete.isEstado() : !paquete.isEstado()) {
                    modelo.addRow(new Object[]{paquete.getIdPaquete(), paquete.getOrigen().getNombre(), paquete.getDestino().getNombre(), paquete.getAloja().getTipo() + "/" + paquete.getAloja().getServicio(), paquete.getCantPersonas()});
                }
            }
        }
    }

    private void borrarFilaDestino() {
        int f = jTable.getRowCount() - 1;
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }

    private void SeleccionarFila() {
        int filas = jTable.getSelectedRow();
        if (filas != -1) {
            CargarTextField(paqueteData.buscarPaquete((int) jTable.getValueAt(filas, 0)));
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        }

    }

    private void CargarTextField(Paquete aux) {
        jtfAlojamiento.setText(aux.getAloja().getTipo());
        jtfOrigen.setText(aux.getOrigen().getNombre() + ", " + aux.getOrigen().getProvincia() + ", " + aux.getOrigen().getPais());
        jtfDestino.setText(aux.getDestino().getNombre() + ", " + aux.getDestino().getProvincia() + ", " + aux.getDestino().getPais());
        jtfFechaIngreso.setText(aux.getAloja().getFechaIn().toString());
        jtfFechaSalida.setText(aux.getAloja().getFechaOn().toString());
        jSpinner1.setValue(aux.getCantPersonas());
        double cantDias = ChronoUnit.DAYS.between(aux.getAloja().getFechaIn(), aux.getAloja().getFechaOn()); //cantidad de dias
        double total = aux.getAloja().getImporteDiario() * cantDias;   //cantidad de dias * el importe diario
        total += aux.getPasa().getImporte();                         //se le suma el transpoirte
        jtfImportePersona.setText("$ " + total);
        jtfImporteTotal.setText("$ " + total * (int) jSpinner1.getValue());
        jtfServicio.setText(aux.getAloja().getServicio());
        jtfTransporte.setText(aux.getPasa().getTransporte());
        
    }

    private void LimpiarTextField() {
        jtfAlojamiento.setText("");
        jtfOrigen.setText("");
        jtfDestino.setText("");
        jtfFechaIngreso.setText("");
        jtfFechaSalida.setText("");
        jtfImportePersona.setText("");
        jtfImporteTotal.setText("");
        jtfServicio.setText("");
        jtfTransporte.setText("");
        jSpinner1.setValue(0);
    }

    private void EliminarDeTabla() {
        int filas = jTable.getSelectedRow();
        if (filas != -1) {
            int idPaquete = (int) jTable.getValueAt(filas, 0);
            if (paqueteData.buscarPaquete(idPaquete).isEstado()) {
                paqueteData.BajaPaquete(idPaquete);
                alojamientoData.BajaAlojamiento(paqueteData.buscarPaquete(idPaquete).getAloja().getIdAlojamiento());
                pasajeData.BajaPasaje(paqueteData.buscarPaquete(idPaquete).getPasa().getIdPasaje());
            } else {
                String title = "Eliminacion Permanente";
                String message = "Si elimina un dato ya eliminado no se podra recuperar\nEsta Seguro?";
                int respuesta = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
                if (respuesta == JOptionPane.YES_OPTION) {
                    int auxAloja = paqueteData.buscarPaquete(idPaquete).getAloja().getIdAlojamiento();
                    int auxpasaje = paqueteData.buscarPaquete(idPaquete).getPasa().getIdPasaje();
                    paqueteData.BajaRealPaquete(idPaquete);
                    alojamientoData.BajaRealAlojamiento(auxAloja);
                    pasajeData.BajaRealPasaje(auxpasaje);

                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        }
        LimpiarTextField();
        CargarTabla();
    }

    private void EnableBottonRecuperar() {
        if (!jCheckBoxEliminados.isSelected()) {
            recuperarButton.setEnabled(false);
            recuperarButton.setFocusable(false);
            recuperarButton.setBackground(new Color(66, 66, 66));

        } else {
            recuperarButton.setEnabled(true);
            recuperarButton.setFocusable(true);
            recuperarButton.setBackground(new Color(47,52,67));
        }
    }

    private void RecuperarPaquete() {
        int filas = jTable.getSelectedRow();
        if (filas != -1) {
            Paquete aux =paqueteData.buscarPaquete((int)jTable.getValueAt(filas, 0));
            aux.setEstado(true);
            aux.getAloja().setEstado(true);
            aux.getPasa().setEstado(true);
            paqueteData.ModificarPaquete(aux.getIdPaquete(),aux);
            alojamientoData.ModificacionAlojamiento(aux.getAloja().getIdAlojamiento(),aux.getAloja());
            pasajeData.ModificacionPasaje(aux.getPasa().getIdPasaje(),aux.getPasa());
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajaButton;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JCheckBox jCheckBoxEliminados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelFull;
    private javax.swing.JPanel jPanelHead;
    private javax.swing.JPanel jPanelNuevo;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel jlabel_exit;
    private javax.swing.JTextField jtfAlojamiento;
    private javax.swing.JTextField jtfDestino;
    private javax.swing.JTextField jtfFechaIngreso;
    private javax.swing.JTextField jtfFechaSalida;
    private javax.swing.JTextField jtfImportePersona;
    private javax.swing.JTextField jtfImporteTotal;
    private javax.swing.JTextField jtfOrigen;
    private javax.swing.JTextField jtfServicio;
    private javax.swing.JTextField jtfTransporte;
    private javax.swing.JButton recuperarButton;
    // End of variables declaration//GEN-END:variables

}
