/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import sistematuristico.AccesoData.PasajeData;
import sistematuristico.Entidades.Ciudad;
import sistematuristico.Entidades.Pasaje;

/**
 *
 * @author crist
 */
public class SeleccionTransporte extends javax.swing.JInternalFrame {

    Ciudad origen = Menu.paquete.getOrigen();
    Ciudad destino = Menu.paquete.getDestino();
    double precio;
    String transporte;
    Pasaje pasajeGlobal;
    PasajeData pasajeData = new PasajeData();
    int colectivo[] = {5000, 10000, 30000};
    int avion[] = {0, 80000, 150000};
    int tren[] = {300, 300, 10000};
    int barco[] = {0, 15000, 40000};

    public SeleccionTransporte() {
        initComponents();
        ActualizarPrecio(CalcularDistancia(origen, destino));
        desactivarOpciones();
        datosPrecargados();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFull = new javax.swing.JPanel();
        jPanelHead = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelBody = new javax.swing.JPanel();
        jPanelBuscar1 = new javax.swing.JPanel();
        jPanelColectivo = new javax.swing.JPanel();
        jbSeleccionarColectivo = new javax.swing.JButton();
        jlPrecioColectivo = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jPanelAvion = new javax.swing.JPanel();
        jbSeleccionarAvion = new javax.swing.JButton();
        jlPrecioAvion = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabelAvion = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jPanelBarco = new javax.swing.JPanel();
        jbSeleccionarBarco = new javax.swing.JButton();
        jlPrecioBarco = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabelBarco = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jPanelTren = new javax.swing.JPanel();
        jbSeleccionarTren = new javax.swing.JButton();
        jlPrecioTren = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jbSiguiente = new javax.swing.JButton();

        jPanelFull.setBackground(new java.awt.Color(56, 63, 79));
        jPanelFull.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHead.setBackground(new java.awt.Color(56, 63, 79));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 237, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione el Transporte");

        jSeparator1.setBackground(new java.awt.Color(235, 237, 255));

        jSeparator2.setBackground(new java.awt.Color(235, 237, 255));

        javax.swing.GroupLayout jPanelHeadLayout = new javax.swing.GroupLayout(jPanelHead);
        jPanelHead.setLayout(jPanelHeadLayout);
        jPanelHeadLayout.setHorizontalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeadLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelHeadLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanelHeadLayout.setVerticalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeadLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanelFull.add(jPanelHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jPanelBody.setBackground(new java.awt.Color(56, 63, 79));
        jPanelBody.setPreferredSize(new java.awt.Dimension(1000, 540));
        jPanelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBuscar1.setBackground(new java.awt.Color(56, 63, 79));

        jPanelColectivo.setBackground(new java.awt.Color(56, 63, 79));
        jPanelColectivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jbSeleccionarColectivo.setBackground(new java.awt.Color(47, 52, 67));
        jbSeleccionarColectivo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSeleccionarColectivo.setForeground(new java.awt.Color(235, 237, 255));
        jbSeleccionarColectivo.setText("Seleccionar");
        jbSeleccionarColectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeleccionarColectivoActionPerformed(evt);
            }
        });

        jlPrecioColectivo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlPrecioColectivo.setForeground(new java.awt.Color(235, 237, 255));
        jlPrecioColectivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPrecioColectivo.setText("$ - - - - -");

        jSeparator11.setBackground(new java.awt.Color(235, 237, 255));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(235, 237, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Colectivo");

        jSeparator12.setBackground(new java.awt.Color(235, 237, 255));

        javax.swing.GroupLayout jPanelColectivoLayout = new javax.swing.GroupLayout(jPanelColectivo);
        jPanelColectivo.setLayout(jPanelColectivoLayout);
        jPanelColectivoLayout.setHorizontalGroup(
            jPanelColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColectivoLayout.createSequentialGroup()
                .addGroup(jPanelColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelColectivoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelColectivoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelColectivoLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jbSeleccionarColectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelColectivoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPrecioColectivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelColectivoLayout.setVerticalGroup(
            jPanelColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColectivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlPrecioColectivo)
                .addGap(18, 18, 18)
                .addComponent(jbSeleccionarColectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanelAvion.setBackground(new java.awt.Color(56, 63, 79));
        jPanelAvion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jbSeleccionarAvion.setBackground(new java.awt.Color(47, 52, 67));
        jbSeleccionarAvion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSeleccionarAvion.setForeground(new java.awt.Color(235, 237, 255));
        jbSeleccionarAvion.setText("Seleccionar");
        jbSeleccionarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeleccionarAvionActionPerformed(evt);
            }
        });

        jlPrecioAvion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlPrecioAvion.setForeground(new java.awt.Color(235, 237, 255));
        jlPrecioAvion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPrecioAvion.setText("$ - - - - -");

        jSeparator13.setBackground(new java.awt.Color(235, 237, 255));

        jLabelAvion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelAvion.setForeground(new java.awt.Color(235, 237, 255));
        jLabelAvion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAvion.setText("Avion");

        jSeparator14.setBackground(new java.awt.Color(235, 237, 255));

        javax.swing.GroupLayout jPanelAvionLayout = new javax.swing.GroupLayout(jPanelAvion);
        jPanelAvion.setLayout(jPanelAvionLayout);
        jPanelAvionLayout.setHorizontalGroup(
            jPanelAvionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAvionLayout.createSequentialGroup()
                .addGroup(jPanelAvionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAvionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAvionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator14))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAvionLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jbSeleccionarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelAvionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelAvionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPrecioAvion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAvion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelAvionLayout.setVerticalGroup(
            jPanelAvionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAvionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabelAvion)
                .addGap(10, 10, 10)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlPrecioAvion)
                .addGap(18, 18, 18)
                .addComponent(jbSeleccionarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanelBarco.setBackground(new java.awt.Color(56, 63, 79));
        jPanelBarco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jbSeleccionarBarco.setBackground(new java.awt.Color(47, 52, 67));
        jbSeleccionarBarco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSeleccionarBarco.setForeground(new java.awt.Color(235, 237, 255));
        jbSeleccionarBarco.setText("Seleccionar");
        jbSeleccionarBarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeleccionarBarcoActionPerformed(evt);
            }
        });

        jlPrecioBarco.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlPrecioBarco.setForeground(new java.awt.Color(235, 237, 255));
        jlPrecioBarco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPrecioBarco.setText("$ - - - - -");

        jSeparator15.setBackground(new java.awt.Color(235, 237, 255));

        jLabelBarco.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelBarco.setForeground(new java.awt.Color(235, 237, 255));
        jLabelBarco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBarco.setText("Barco");

        jSeparator16.setBackground(new java.awt.Color(235, 237, 255));

        javax.swing.GroupLayout jPanelBarcoLayout = new javax.swing.GroupLayout(jPanelBarco);
        jPanelBarco.setLayout(jPanelBarcoLayout);
        jPanelBarcoLayout.setHorizontalGroup(
            jPanelBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBarcoLayout.createSequentialGroup()
                .addGroup(jPanelBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBarcoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBarcoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBarcoLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jbSeleccionarBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelBarcoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPrecioBarco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBarco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelBarcoLayout.setVerticalGroup(
            jPanelBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBarcoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBarco)
                .addGap(10, 10, 10)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlPrecioBarco)
                .addGap(18, 18, 18)
                .addComponent(jbSeleccionarBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanelTren.setBackground(new java.awt.Color(56, 63, 79));
        jPanelTren.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jbSeleccionarTren.setBackground(new java.awt.Color(47, 52, 67));
        jbSeleccionarTren.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSeleccionarTren.setForeground(new java.awt.Color(235, 237, 255));
        jbSeleccionarTren.setText("Seleccionar");
        jbSeleccionarTren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeleccionarTrenActionPerformed(evt);
            }
        });

        jlPrecioTren.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlPrecioTren.setForeground(new java.awt.Color(235, 237, 255));
        jlPrecioTren.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPrecioTren.setText("$ - - - - -");

        jSeparator17.setBackground(new java.awt.Color(235, 237, 255));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(235, 237, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Tren");

        jSeparator18.setBackground(new java.awt.Color(235, 237, 255));

        javax.swing.GroupLayout jPanelTrenLayout = new javax.swing.GroupLayout(jPanelTren);
        jPanelTren.setLayout(jPanelTrenLayout);
        jPanelTrenLayout.setHorizontalGroup(
            jPanelTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrenLayout.createSequentialGroup()
                .addGroup(jPanelTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTrenLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTrenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator18))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTrenLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jbSeleccionarTren, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelTrenLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPrecioTren, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelTrenLayout.setVerticalGroup(
            jPanelTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(10, 10, 10)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlPrecioTren)
                .addGap(18, 18, 18)
                .addComponent(jbSeleccionarTren, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanelBuscar1Layout = new javax.swing.GroupLayout(jPanelBuscar1);
        jPanelBuscar1.setLayout(jPanelBuscar1Layout);
        jPanelBuscar1Layout.setHorizontalGroup(
            jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscar1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelColectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBarco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanelBuscar1Layout.setVerticalGroup(
            jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscar1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelColectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTren, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBarco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        jPanelBody.add(jPanelBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jbSiguiente.setBackground(new java.awt.Color(47, 52, 67));
        jbSiguiente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSiguiente.setForeground(new java.awt.Color(235, 237, 255));
        jbSiguiente.setText("Siguiente");
        jbSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSiguienteActionPerformed(evt);
            }
        });
        jPanelBody.add(jbSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 475, 130, 45));

        jPanelFull.add(jPanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFull, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSiguienteActionPerformed

        Pasaje pasaje = new Pasaje(transporte, precio, origen, true);
        System.out.println(destino);
        System.out.println(destino.getIdCiudad());

        if (Menu.paquete.getPasa() == null) { //Entra si es la primera vez creando el Pasaje
            Menu.paquete.setPasa(pasaje);
        }
        if (Menu.paquete.getPasa().getIdPasaje() == 0) { //Entra si es 0 no paso por SQL
            Menu.guardarIdTransporte = pasajeData.AltaPasaje(Menu.paquete.getPasa()); //ahora id tiene valor y lo guardamos en "guardarIdTransporte" y ademas creamos el sql
        } else {
            Menu.guardarIdTransporte = Menu.paquete.getPasa().getIdPasaje();    //guardamos  en "guardarIdTransporte" el id, y no creamos el sql porque ya estaba
            Menu.paquete.setPasa(pasaje);
            pasajeData.ModificacionPasaje(Menu.guardarIdTransporte, Menu.paquete.getPasa());
        }
        Menu.InternalNum = 4;
        InvocarJInternalFrame(new ResumenPaquete());
    }//GEN-LAST:event_jbSiguienteActionPerformed

    private void jbSeleccionarColectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeleccionarColectivoActionPerformed
        precio = colectivo[CalcularDistancia(origen, destino)];
        transporte = "Colectivo";
        seleccionFocus(transporte);
    }//GEN-LAST:event_jbSeleccionarColectivoActionPerformed

    private void jbSeleccionarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeleccionarAvionActionPerformed
        precio = avion[CalcularDistancia(origen, destino)];
        transporte = "Avion";
        seleccionFocus(transporte);

    }//GEN-LAST:event_jbSeleccionarAvionActionPerformed

    private void jbSeleccionarBarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeleccionarBarcoActionPerformed
        precio = barco[CalcularDistancia(origen, destino)];
        transporte = "Barco";
        seleccionFocus(transporte);

    }//GEN-LAST:event_jbSeleccionarBarcoActionPerformed

    private void jbSeleccionarTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeleccionarTrenActionPerformed
        precio = tren[CalcularDistancia(origen, destino)];
        transporte = "Tren";
        seleccionFocus(transporte);

    }//GEN-LAST:event_jbSeleccionarTrenActionPerformed

    private int CalcularDistancia(Ciudad origen, Ciudad destino) {
        if (!(origen.getPais().equalsIgnoreCase(destino.getPais()))) {
            return 2;//es internacional
        } else if (!origen.getProvincia().equalsIgnoreCase(destino.getProvincia())) {
            return 1;//es interprovincial 
        } else {
            return 0;
        }
    }

    private void ActualizarPrecio(int distancia) {
        jlPrecioColectivo.setText("$ " + colectivo[distancia]);
        jlPrecioAvion.setText("$ " + avion[distancia]);
        jlPrecioTren.setText("$ " + tren[distancia]);
        jlPrecioBarco.setText("$ " + barco[distancia]);

    }

    private void InvocarJInternalFrame(JInternalFrame frame) {
        BasicInternalFrameUI ui = (BasicInternalFrameUI) frame.getUI();
        ui.setNorthPane(null);
        frame.setBorder(null); // Elimina el borde
        frame.setClosable(false); // Desactiva la opción de cerrar
        frame.setIconifiable(false); // Desactiva la opción de minimizar
        frame.setOpaque(true); // Hace que el contenido sea opaco
        frame.setSize(Menu.Escritorio.getSize()); // Establece el tamaño igual al del desktopPane
        frame.setVisible(true); // Lo hace visible
        Menu.Escritorio.add(frame); // Agrega el JInternalFrame al JDesktopPane
        frame.toFront();
    }

    private void datosPrecargados() {
        if (Menu.paquete.getPasa() != null) {
            transporte = Menu.paquete.getPasa().getTransporte();
            precio = Menu.paquete.getPasa().getImporte();
            seleccionFocus(transporte);
        } else {
            seleccionFocus("");
        }
    }

    private void seleccionFocus(String text) {
        jPanelColectivo.setBorder(new LineBorder(new Color(235, 237, 255), 3));
        jPanelAvion.setBorder(new LineBorder(new Color(235, 237, 255), 3));
        jPanelTren.setBorder(new LineBorder(new Color(235, 237, 255), 3));
        jPanelBarco.setBorder(new LineBorder(new Color(235, 237, 255), 3));
        switch (text) {
            case "Colectivo":
                jPanelColectivo.setBorder(new LineBorder(new Color(83, 81, 251), 3));
                break;
            case "Avion":
                jPanelAvion.setBorder(new LineBorder(new Color(83, 81, 251), 3));
                break;
            case "Tren":
                jPanelTren.setBorder(new LineBorder(new Color(83, 81, 251), 3));
                break;
            case "Barco":
                jPanelBarco.setBorder(new LineBorder(new Color(83, 81, 251), 3));
                break;
            default:
                jPanelColectivo.setBorder(new LineBorder(new Color(235, 237, 255), 3));
                jPanelAvion.setBorder(new LineBorder(new Color(235, 237, 255), 3));
                jPanelTren.setBorder(new LineBorder(new Color(235, 237, 255), 3));
                jPanelBarco.setBorder(new LineBorder(new Color(235, 237, 255), 3));
        }
        //Boton siguiente se habilita
        if (!((text.equalsIgnoreCase("Avion")&&avion[CalcularDistancia(origen, destino)] == 0)||(text.equalsIgnoreCase("Barco")&&barco[CalcularDistancia(origen, destino)]==0))) {
            jbSiguiente.setFocusable(true);
            jbSiguiente.setEnabled(true);
            jbSiguiente.setBackground(new Color(56, 63, 79));
        }
    }

    private void desactivarOpciones() {
        //Boton siguiente se deshabilita
        jbSiguiente.setFocusable(false);
        jbSiguiente.setEnabled(false);
        jbSiguiente.setBackground(new Color(66, 66, 66));
        
        //el panel de avion y barco se activan por si venian desactivados de antes [no se si es posible es por las dudas]
        enabledPanelAvion(true);
        enabledPanelBarco(true);
        //se deshabilita avion o barco si el importe es 0
        if (avion[CalcularDistancia(origen, destino)] == 0) {
            enabledPanelAvion(false);
        }
        if (barco[CalcularDistancia(origen, destino)] == 0) {
           enabledPanelBarco(false);
        }
    }
    private void enabledPanelAvion(boolean flag){
        jbSeleccionarAvion.setFocusable(flag);
        jbSeleccionarAvion.setEnabled(flag);
        jbSeleccionarAvion.setBackground(flag?new Color(47,52,67):new Color(66, 66, 66));
        jlPrecioAvion.setText(flag?"$ " + avion[CalcularDistancia(origen, destino)]:"$ - - - - -");
        jlPrecioAvion.setForeground(flag?new Color(235,237,255):new Color(155, 155, 155));
        jLabelAvion.setForeground(flag?new Color(235,237,255):new Color(155, 155, 155));
        jPanelAvion.setBorder(flag?new LineBorder(new Color(235, 237, 255), 3):new LineBorder(new Color(155, 155, 155), 3));
        jSeparator13.setForeground(flag?new Color(235,237,255):new Color(155, 155, 155));
        jSeparator14.setForeground(flag?new Color(235,237,255):new Color(155, 155, 155));
    }
    private void enabledPanelBarco(boolean flag){
        jbSeleccionarBarco.setFocusable(flag);
        jbSeleccionarBarco.setEnabled(flag);
        jbSeleccionarBarco.setBackground(flag?new Color(47,52,67):new Color(66, 66, 66));
        jlPrecioBarco.setText(flag?"$ " + avion[CalcularDistancia(origen, destino)]:"$ - - - - -");
        jlPrecioBarco.setForeground(flag?new Color(235,237,255):new Color(155, 155, 155));
        jLabelBarco.setForeground(flag?new Color(235,237,255):new Color(155, 155, 155));
        jPanelBarco.setBorder(flag?new LineBorder(new Color(235, 237, 255), 3):new LineBorder(new Color(155, 155, 155), 3));
        jSeparator15.setForeground(flag?new Color(235,237,255):new Color(155, 155, 155));
        jSeparator16.setForeground(flag?new Color(235,237,255):new Color(155, 155, 155));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAvion;
    private javax.swing.JLabel jLabelBarco;
    private javax.swing.JPanel jPanelAvion;
    private javax.swing.JPanel jPanelBarco;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelBuscar1;
    private javax.swing.JPanel jPanelColectivo;
    private javax.swing.JPanel jPanelFull;
    private javax.swing.JPanel jPanelHead;
    private javax.swing.JPanel jPanelTren;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbSeleccionarAvion;
    private javax.swing.JButton jbSeleccionarBarco;
    private javax.swing.JButton jbSeleccionarColectivo;
    private javax.swing.JButton jbSeleccionarTren;
    private javax.swing.JButton jbSiguiente;
    private javax.swing.JLabel jlPrecioAvion;
    private javax.swing.JLabel jlPrecioBarco;
    private javax.swing.JLabel jlPrecioColectivo;
    private javax.swing.JLabel jlPrecioTren;
    // End of variables declaration//GEN-END:variables
}
