/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import sistematuristico.AccesoData.AlojamientoData;
import sistematuristico.Entidades.Alojamiento;

import sistematuristico.AccesoData.AlojamientoData;

import sistematuristico.Entidades.Alojamiento;

/**
 *
 * @author crist
 */
public class SeleccionAlojamiento extends javax.swing.JInternalFrame {

    Alojamiento alojamiento;
    AlojamientoData alojamientoData = new AlojamientoData();

    public SeleccionAlojamiento() {
        initComponents();
        cargarcombobox();

        jTextCiudad.setText(Menu.paquete.getDestino().getNombre() + ", " + Menu.paquete.getDestino().getProvincia() + ", " + Menu.paquete.getDestino().getPais());
        if (Menu.paquete.getAloja() != null) {
            LocalDate ldate = (Menu.paquete.getAloja().getFechaIn());

            jDateChooserInicio.setDate(Date.from(Menu.paquete.getAloja().getFechaIn().atStartOfDay(ZoneId.systemDefault()).toInstant()));
            jDateChooserSalida.setDate(Date.from(Menu.paquete.getAloja().getFechaOn().atStartOfDay(ZoneId.systemDefault()).toInstant()));
            jComboBoxAlojamiento.setSelectedItem(Menu.paquete.getAloja().getTipo());
            jComboBoxServicio.setSelectedItem(Menu.paquete.getAloja().getServicio());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFull = new javax.swing.JPanel();
        jPanelHead = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelBody = new javax.swing.JPanel();
        jPanelNuevo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextCiudad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxServicio = new javax.swing.JComboBox<>();
        jComboBoxAlojamiento = new javax.swing.JComboBox<>();
        jTextAlojamiento = new javax.swing.JTextField();
        jDateChooserInicio = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jDateChooserSalida = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextServicio = new javax.swing.JTextField();
        jTextTotal = new javax.swing.JTextField();
        jButtonConfirmar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextDiario = new javax.swing.JTextField();

        jPanelFull.setBackground(new java.awt.Color(56, 63, 79));
        jPanelFull.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHead.setBackground(new java.awt.Color(56, 63, 79));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 237, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione el Alojamiento");

        jSeparator1.setBackground(new java.awt.Color(235, 237, 255));

        jSeparator2.setBackground(new java.awt.Color(235, 237, 255));

        javax.swing.GroupLayout jPanelHeadLayout = new javax.swing.GroupLayout(jPanelHead);
        jPanelHead.setLayout(jPanelHeadLayout);
        jPanelHeadLayout.setHorizontalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeadLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelHeadLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanelHeadLayout.setVerticalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeadLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelFull.add(jPanelHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jPanelBody.setBackground(new java.awt.Color(56, 63, 79));
        jPanelBody.setPreferredSize(new java.awt.Dimension(1000, 540));

        jPanelNuevo.setBackground(new java.awt.Color(56, 63, 79));

        jPanel1.setBackground(new java.awt.Color(56, 63, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(235, 237, 255));
        jLabel6.setText("Fecha de Ingreso:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 154, 38));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(235, 237, 255));
        jLabel10.setText("Tipo de Alojamiento:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 154, 38));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(235, 237, 255));
        jLabel11.setText("Importe Diario:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 154, 38));

        jTextCiudad.setEditable(false);
        jTextCiudad.setBackground(new java.awt.Color(56, 63, 79));
        jTextCiudad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextCiudad.setForeground(new java.awt.Color(235, 237, 255));
        jTextCiudad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jTextCiudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextCiudadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextCiudadFocusLost(evt);
            }
        });
        jPanel1.add(jTextCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 296, 38));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(235, 237, 255));
        jLabel13.setText("Importe Total:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 107, 38));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(235, 237, 255));
        jLabel14.setText("Tipo de Servicio");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 154, 38));

        jComboBoxServicio.setForeground(new java.awt.Color(56, 63, 79));
        jComboBoxServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServicioActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 160, -1));

        jComboBoxAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlojamientoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxAlojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 160, -1));

        jTextAlojamiento.setEditable(false);
        jTextAlojamiento.setBackground(new java.awt.Color(56, 63, 79));
        jTextAlojamiento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextAlojamiento.setForeground(new java.awt.Color(235, 237, 255));
        jTextAlojamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jTextAlojamiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextAlojamientoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAlojamientoFocusLost(evt);
            }
        });
        jPanel1.add(jTextAlojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 81, 38));

        jDateChooserInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserInicioPropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooserInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 160, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(235, 237, 255));
        jLabel16.setText("Fecha de Salida:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 154, 38));

        jDateChooserSalida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserSalidaPropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooserSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(235, 237, 255));
        jLabel17.setText("$:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, 38));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(235, 237, 255));
        jLabel18.setText("$:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, 38));

        jTextServicio.setEditable(false);
        jTextServicio.setBackground(new java.awt.Color(56, 63, 79));
        jTextServicio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextServicio.setForeground(new java.awt.Color(235, 237, 255));
        jTextServicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jTextServicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextServicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextServicioFocusLost(evt);
            }
        });
        jPanel1.add(jTextServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 81, 38));

        jTextTotal.setBackground(new java.awt.Color(56, 63, 79));
        jTextTotal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextTotal.setForeground(new java.awt.Color(235, 237, 255));
        jTextTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jTextTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextTotalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextTotalFocusLost(evt);
            }
        });
        jPanel1.add(jTextTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 160, 38));

        jButtonConfirmar.setBackground(new java.awt.Color(47, 52, 67));
        jButtonConfirmar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonConfirmar.setForeground(new java.awt.Color(235, 237, 255));
        jButtonConfirmar.setText("Siguiente");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 130, 45));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(235, 237, 255));
        jLabel7.setText("Ciudad Destino");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 154, 38));

        jTextDiario.setEditable(false);
        jTextDiario.setBackground(new java.awt.Color(56, 63, 79));
        jTextDiario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextDiario.setForeground(new java.awt.Color(235, 237, 255));
        jTextDiario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jTextDiario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextDiarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDiarioFocusLost(evt);
            }
        });
        jTextDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDiarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 160, 38));

        javax.swing.GroupLayout jPanelNuevoLayout = new javax.swing.GroupLayout(jPanelNuevo);
        jPanelNuevo.setLayout(jPanelNuevoLayout);
        jPanelNuevoLayout.setHorizontalGroup(
            jPanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNuevoLayout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );
        jPanelNuevoLayout.setVerticalGroup(
            jPanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelFull.add(jPanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFull, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCiudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextCiudadFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCiudadFocusGained

    private void jTextCiudadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextCiudadFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCiudadFocusLost

    private void jTextAlojamientoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAlojamientoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlojamientoFocusGained

    private void jTextAlojamientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAlojamientoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlojamientoFocusLost

    private void jTextServicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextServicioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextServicioFocusGained

    private void jTextServicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextServicioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextServicioFocusLost

    private void jTextTotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextTotalFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTotalFocusGained

    private void jTextTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextTotalFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTotalFocusLost

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
       int a;//variable para permitir realizar el alta o la modicicacion si cumple con las condiciones previas
        try {
            Alojamiento aloja = new Alojamiento();

            aloja.setFechaIn(jDateChooserInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            aloja.setFechaOn(jDateChooserSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            //aloja.setDestino(completar);
            aloja.setTipo(String.valueOf(jComboBoxAlojamiento.getSelectedItem()));
            aloja.setServicio(String.valueOf(jComboBoxServicio.getSelectedItem()));
            aloja.setEstado(true);
            aloja.setDestino(Menu.paquete.getDestino());
            //double precio = Double.parseDouble(jTextServicio.getText()) + Double.parseDouble(jTextServicio.getText());
            aloja.setImporteDiario(Double.parseDouble(jTextDiario.getText()));
            alojamiento = aloja;
            a=1;

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "error al ingresar datos");
            a=0;
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Error. No debe haber campos vacios");
            a=0;
        }
        if(a==1){
        try {
            Menu.guardarIdAlojamiento = Menu.paquete.getAloja().getIdAlojamiento();
            alojamientoData.ModificacionAlojamiento(Menu.guardarIdAlojamiento, alojamiento);
        } catch (NullPointerException ex) {
            alojamientoData.AltaAlojamiento(alojamiento);
            Menu.guardarIdAlojamiento = alojamiento.getIdAlojamiento();
        }
        Menu.paquete.setAloja(alojamiento);
        Menu.InternalNum = 3;
        InvocarJInternalFrame(new SeleccionTransporte());
        }else{
            JOptionPane.showMessageDialog(null, "no se pudo completar la operacion");
        }

    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jComboBoxAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlojamientoActionPerformed
       seleAloja();
        precioDiario();


    }//GEN-LAST:event_jComboBoxAlojamientoActionPerformed

    private void jTextDiarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDiarioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDiarioFocusGained

    private void jTextDiarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDiarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDiarioFocusLost

    private void jComboBoxServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServicioActionPerformed
       seleServi();
        precioDiario();
    }//GEN-LAST:event_jComboBoxServicioActionPerformed

    private void jDateChooserInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserInicioPropertyChange
        try {
            LocalDate fechaActual = LocalDate.now();
            LocalDate fecha2 = jDateChooserInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fecha1 = fechaActual;
            long diferenciaDias1 = ChronoUnit.DAYS.between(fecha1, fecha2);
            long diferenciaDias2 = 1;
            if (jDateChooserSalida.getDate() != null) {
                LocalDate fecha3 = jDateChooserSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                diferenciaDias2 = ChronoUnit.DAYS.between(fecha2, fecha3);
            }
            if (diferenciaDias1 >= 0 && diferenciaDias2 > 0) {
                seleServi();
                seleAloja();
                precioDiario();
                
            } else {
                JOptionPane.showMessageDialog(null, "La fecha no puede ser anterior a la actual o posterior a la feha de salida");
                jDateChooserInicio.setDate(null);
            }
        } catch (NullPointerException ex) {
        }
    }//GEN-LAST:event_jDateChooserInicioPropertyChange

    private void jDateChooserSalidaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserSalidaPropertyChange

        try {
            LocalDate fechaActual = LocalDate.now();
            LocalDate fecha2 = jDateChooserSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fecha1 = fechaActual;
            if (jDateChooserInicio.getDate() != null) {
                fecha1 = jDateChooserInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            }
            long diferenciaDias = ChronoUnit.DAYS.between(fecha1, fecha2);
            if (diferenciaDias > 0) {
                seleServi();
                seleAloja();
                precioDiario();
            } else {
                JOptionPane.showMessageDialog(null, "La fecha no puede ser anterior seleccionada en Fecha Inicio ni a la fecha actual");
                jDateChooserSalida.setDate(null);
            }
        } catch (NullPointerException ex) {
        }
    }//GEN-LAST:event_jDateChooserSalidaPropertyChange

    private void jTextDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDiarioActionPerformed
    // </editor-fold>
    // </editor-fold>  

    private void textBorderFocusGained(JTextField textField) {
        textField.setBorder(new LineBorder(new Color(83, 81, 251), 3));
    }

    private void textBorderFocusLost(JTextField textField) {
        textField.setBorder(new LineBorder(new Color(235, 237, 255), 1));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxAlojamiento;
    private javax.swing.JComboBox<String> jComboBoxServicio;
    private com.toedter.calendar.JDateChooser jDateChooserInicio;
    private com.toedter.calendar.JDateChooser jDateChooserSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelFull;
    private javax.swing.JPanel jPanelHead;
    private javax.swing.JPanel jPanelNuevo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextAlojamiento;
    private javax.swing.JTextField jTextCiudad;
    private javax.swing.JTextField jTextDiario;
    private javax.swing.JTextField jTextServicio;
    private javax.swing.JTextField jTextTotal;
    // End of variables declaration//GEN-END:variables
private void cargarcombobox() {
        //combo alojamiento
        jComboBoxAlojamiento.setForeground(new Color(235,237,255));
        jComboBoxAlojamiento.setBackground(new Color(56,63,79));
        jComboBoxAlojamiento.addItem("Hotel");
        jComboBoxAlojamiento.addItem("Hostel");
        jComboBoxAlojamiento.addItem("Casa");
        jComboBoxAlojamiento.addItem("Cabaña");
        //combo servicio
        jComboBoxServicio.setForeground(new Color(235,237,255));
        jComboBoxServicio.setBackground(new Color(56,63,79));
        jComboBoxServicio.addItem("Clasico");
        jComboBoxServicio.addItem("Desayuno");
        jComboBoxServicio.addItem("Media Pension");
        jComboBoxServicio.addItem("Todo Incluido");
    }

    private void limpiar() {
        jComboBoxAlojamiento.setSelectedIndex(-1);
        jComboBoxServicio.setSelectedIndex(-1);
        jDateChooserInicio.setDate(null);
        jDateChooserSalida.setDate(null);
        jTextDiario.setText("");
        jTextTotal.setText("");
        jTextServicio.setText("");
        jTextAlojamiento.setText("");
    }

    private void precioDiario() {
        if (!(jTextAlojamiento.getText().isEmpty() || jTextServicio.getText().isEmpty())) {
            jTextDiario.setText((Double.parseDouble(jTextAlojamiento.getText()) + Double.parseDouble(jTextServicio.getText()) )+ "");
            if (jDateChooserInicio.getDate() == null || jDateChooserSalida.getDate() == null) {
                jTextTotal.setText(null);
            } else {
                LocalDate fecha1 = jDateChooserInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                LocalDate fecha2 = jDateChooserSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                long diferenciaDias = ChronoUnit.DAYS.between(fecha1, fecha2);
                jTextTotal.setText(String.valueOf(Double.valueOf(jTextDiario.getText()) * diferenciaDias + ""));
            }
        }
    }
    private void seleServi(){
         switch (String.valueOf(jComboBoxServicio.getSelectedItem())) {
           
            case "Clasico":
                jTextServicio.setText(String.valueOf(0*temporada()));
                break;
            case "Desayuno":
                jTextServicio.setText(String.valueOf(300*temporada()));
                break;
            case "Media Pension":
                jTextServicio.setText(String.valueOf(500*temporada()));
                break;
            case "Todo Incluido":
                jTextServicio.setText(String.valueOf(1000*temporada()));
                break;
            default:

        }
    }
    private void seleAloja(){
         switch (String.valueOf(jComboBoxAlojamiento.getSelectedItem())) {
            
            case "Hotel":
                jTextAlojamiento.setText(String.valueOf( Math.round(3000*temporada())));
                break;
            case "Hostel":
                jTextAlojamiento.setText(String.valueOf(String.format("%.2f",1500*temporada())));
                System.out.println((String.valueOf(String.format("%.2f",1500*temporada()))));
                break;
            case "Casa":
                jTextAlojamiento.setText(String.valueOf(String.format("%.2f",2000*temporada())));
                break;
            case "Cabaña":
                jTextAlojamiento.setText(String.valueOf(String.format("%.2f",2500*temporada())));
                break;
            default:

        }
    }
    private double temporada(){
         double precioTemporada= 1;
    
        try{
        LocalDate inicio=jDateChooserInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
       
       
        if(inicio.getMonthValue()<3|| inicio.getMonthValue()>11){
             precioTemporada= 1.3;
        }
        if(inicio.getMonthValue()>8&& inicio.getMonthValue()<12){
             precioTemporada= 1.15;
        }
        return precioTemporada;
    }catch(NullPointerException ex){
        return precioTemporada;
    }
    }

    private void InvocarJInternalFrame(JInternalFrame frame) {
        BasicInternalFrameUI ui = (BasicInternalFrameUI) frame.getUI();
        ui.setNorthPane(null);
        frame.setBorder(null); // Elimina el borde
        frame.setClosable(false); // Desactiva la opción de cerrar
        frame.setIconifiable(false); // Desactiva la opción de minimizar
        frame.setOpaque(true); // Hace que el contenido sea opaco
        frame.setSize(Menu.Escritorio.getSize()); // Establece el tamaño igual al del desktopPane
        frame.setVisible(true); // Lo hace visible
        Menu.Escritorio.add(frame); // Agrega el JInternalFrame al JDesktopPane
        frame.toFront();
    }
    /**
     * private void recuperarDatos() { try { if (Menu.guardarIdAlojamiento !=0)
     * {
     * jComboBoxAlojamiento.setSelectedItem(Menu.paquete.getAloja().getTipo());
     * jComboBoxServicio.setSelectedItem(Menu.paquete.getAloja().getServicio());
     * jDateChooserInicio.setDate(Date.from(Menu.paquete.getAloja().getFechaIn().atStartOfDay(ZoneId.systemDefault()).toInstant()));
     * jDateChooserSalida.setDate(Date.from(Menu.paquete.getAloja().getFechaOn().atStartOfDay(ZoneId.systemDefault()).toInstant()));
     * precioDiario();
     *
     * }
     * } catch (NullPointerException ex) {
     *
     * }
     * }
     *
     */

}
