/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import sistematuristico.AccesoData.CiudadData;
import sistematuristico.Entidades.Ciudad;

/**
 *
 * @author crist
 */
public class SeleccionCiudad extends javax.swing.JInternalFrame {

    private CiudadData ciudadData = new CiudadData();

    private DefaultTableModel modeloOrigen = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    private DefaultTableModel modeloDestino = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    public SeleccionCiudad() {
        initComponents();
        CrearTabla();
        actualizarTabla("Destino");
        actualizarTabla("Origen");
        botonFocusSeiguiente();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFull = new javax.swing.JPanel();
        jPanelHead = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JPanel();
        jlabel_exit = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jPanelBuscar = new javax.swing.JPanel();
        jbSeleccionarDestino = new javax.swing.JButton();
        jtfBuscarProvinciaDestino = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfBuscarPaisDestino = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfBuscarCiudadDestino = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDestino = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanelBuscar1 = new javax.swing.JPanel();
        jbSeleccionarOrigen = new javax.swing.JButton();
        jtfBuscarProvinciaOrigen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfBuscarPaisOrigen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfBuscarCiudadOrigen = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOrigen = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jbSiguiente = new javax.swing.JButton();

        jPanelFull.setBackground(new java.awt.Color(56, 63, 79));
        jPanelFull.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHead.setBackground(new java.awt.Color(56, 63, 79));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 237, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione Oigen y Destino");

        jSeparator1.setBackground(new java.awt.Color(235, 237, 255));

        jSeparator2.setBackground(new java.awt.Color(235, 237, 255));

        btnSalir.setBackground(new java.awt.Color(56, 63, 79));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });

        jlabel_exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlabel_exit.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_Exit_25px.png"))); // NOI18N

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlabel_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelHeadLayout = new javax.swing.GroupLayout(jPanelHead);
        jPanelHead.setLayout(jPanelHeadLayout);
        jPanelHeadLayout.setHorizontalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeadLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelHeadLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelHeadLayout.setVerticalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeadLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanelFull.add(jPanelHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jPanelBody.setBackground(new java.awt.Color(56, 63, 79));
        jPanelBody.setPreferredSize(new java.awt.Dimension(1000, 540));

        jPanelBuscar.setBackground(new java.awt.Color(56, 63, 79));

        jbSeleccionarDestino.setBackground(new java.awt.Color(47, 52, 67));
        jbSeleccionarDestino.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSeleccionarDestino.setForeground(new java.awt.Color(235, 237, 255));
        jbSeleccionarDestino.setText("Seleccionar");
        jbSeleccionarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeleccionarDestinoActionPerformed(evt);
            }
        });

        jtfBuscarProvinciaDestino.setBackground(new java.awt.Color(56, 63, 79));
        jtfBuscarProvinciaDestino.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfBuscarProvinciaDestino.setForeground(new java.awt.Color(235, 237, 255));
        jtfBuscarProvinciaDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfBuscarProvinciaDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfBuscarProvinciaDestinoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscarProvinciaDestinoFocusLost(evt);
            }
        });
        jtfBuscarProvinciaDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarProvinciaDestinoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBuscarProvinciaDestinoKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(235, 237, 255));
        jLabel8.setText("Nombre Provinia:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(235, 237, 255));
        jLabel9.setText("Nombre Pais:");

        jtfBuscarPaisDestino.setBackground(new java.awt.Color(56, 63, 79));
        jtfBuscarPaisDestino.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfBuscarPaisDestino.setForeground(new java.awt.Color(235, 237, 255));
        jtfBuscarPaisDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfBuscarPaisDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfBuscarPaisDestinoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscarPaisDestinoFocusLost(evt);
            }
        });
        jtfBuscarPaisDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarPaisDestinoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBuscarPaisDestinoKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(235, 237, 255));
        jLabel10.setText("Nombre Ciudad:");

        jtfBuscarCiudadDestino.setBackground(new java.awt.Color(56, 63, 79));
        jtfBuscarCiudadDestino.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfBuscarCiudadDestino.setForeground(new java.awt.Color(235, 237, 255));
        jtfBuscarCiudadDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfBuscarCiudadDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfBuscarCiudadDestinoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscarCiudadDestinoFocusLost(evt);
            }
        });
        jtfBuscarCiudadDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarCiudadDestinoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBuscarCiudadDestinoKeyTyped(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(56, 63, 79));
        jScrollPane1.setForeground(new java.awt.Color(56, 63, 79));

        jTableDestino.setBackground(new java.awt.Color(56, 63, 79));
        jTableDestino.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableDestino.setForeground(new java.awt.Color(235, 237, 255));
        jTableDestino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDestino.setFocusable(false);
        jTableDestino.setGridColor(new java.awt.Color(47, 52, 67));
        jTableDestino.setSelectionBackground(new java.awt.Color(83, 81, 251));
        jTableDestino.setSelectionForeground(new java.awt.Color(235, 237, 255));
        jTableDestino.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTableDestino);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 237, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Destino");

        jSeparator5.setBackground(new java.awt.Color(235, 237, 255));

        jSeparator6.setBackground(new java.awt.Color(235, 237, 255));

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfBuscarCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtfBuscarProvinciaDestino, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtfBuscarPaisDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbSeleccionarDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(jtfBuscarCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jtfBuscarProvinciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBuscarPaisDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSeleccionarDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jSeparator3.setBackground(new java.awt.Color(235, 237, 255));
        jSeparator3.setForeground(new java.awt.Color(235, 237, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanelBuscar1.setBackground(new java.awt.Color(56, 63, 79));

        jbSeleccionarOrigen.setBackground(new java.awt.Color(47, 52, 67));
        jbSeleccionarOrigen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSeleccionarOrigen.setForeground(new java.awt.Color(235, 237, 255));
        jbSeleccionarOrigen.setText("Seleccionar");
        jbSeleccionarOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeleccionarOrigenActionPerformed(evt);
            }
        });

        jtfBuscarProvinciaOrigen.setBackground(new java.awt.Color(56, 63, 79));
        jtfBuscarProvinciaOrigen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfBuscarProvinciaOrigen.setForeground(new java.awt.Color(235, 237, 255));
        jtfBuscarProvinciaOrigen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfBuscarProvinciaOrigen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfBuscarProvinciaOrigenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscarProvinciaOrigenFocusLost(evt);
            }
        });
        jtfBuscarProvinciaOrigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarProvinciaOrigenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBuscarProvinciaOrigenKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(235, 237, 255));
        jLabel11.setText("Nombre Provinia:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(235, 237, 255));
        jLabel12.setText("Nombre Pais:");

        jtfBuscarPaisOrigen.setBackground(new java.awt.Color(56, 63, 79));
        jtfBuscarPaisOrigen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfBuscarPaisOrigen.setForeground(new java.awt.Color(235, 237, 255));
        jtfBuscarPaisOrigen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfBuscarPaisOrigen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfBuscarPaisOrigenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscarPaisOrigenFocusLost(evt);
            }
        });
        jtfBuscarPaisOrigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarPaisOrigenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBuscarPaisOrigenKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(235, 237, 255));
        jLabel13.setText("Nombre Ciudad:");

        jtfBuscarCiudadOrigen.setBackground(new java.awt.Color(56, 63, 79));
        jtfBuscarCiudadOrigen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfBuscarCiudadOrigen.setForeground(new java.awt.Color(235, 237, 255));
        jtfBuscarCiudadOrigen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 237, 255)));
        jtfBuscarCiudadOrigen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfBuscarCiudadOrigenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscarCiudadOrigenFocusLost(evt);
            }
        });
        jtfBuscarCiudadOrigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarCiudadOrigenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBuscarCiudadOrigenKeyTyped(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(56, 63, 79));
        jScrollPane2.setForeground(new java.awt.Color(56, 63, 79));

        jTableOrigen.setBackground(new java.awt.Color(56, 63, 79));
        jTableOrigen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableOrigen.setForeground(new java.awt.Color(235, 237, 255));
        jTableOrigen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableOrigen.setFocusable(false);
        jTableOrigen.setGridColor(new java.awt.Color(47, 52, 67));
        jTableOrigen.setSelectionBackground(new java.awt.Color(83, 81, 251));
        jTableOrigen.setSelectionForeground(new java.awt.Color(235, 237, 255));
        jTableOrigen.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTableOrigen);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(235, 237, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Origen");

        jSeparator7.setBackground(new java.awt.Color(235, 237, 255));

        jSeparator8.setBackground(new java.awt.Color(235, 237, 255));

        javax.swing.GroupLayout jPanelBuscar1Layout = new javax.swing.GroupLayout(jPanelBuscar1);
        jPanelBuscar1.setLayout(jPanelBuscar1Layout);
        jPanelBuscar1Layout.setHorizontalGroup(
            jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscar1Layout.createSequentialGroup()
                .addGroup(jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscar1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBuscar1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelBuscar1Layout.createSequentialGroup()
                                .addGroup(jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfBuscarCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtfBuscarProvinciaOrigen, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtfBuscarPaisOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbSeleccionarOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        jPanelBuscar1Layout.setVerticalGroup(
            jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscar1Layout.createSequentialGroup()
                        .addComponent(jtfBuscarCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jtfBuscarProvinciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBuscarPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBuscar1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSeleccionarOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jbSiguiente.setBackground(new java.awt.Color(47, 52, 67));
        jbSiguiente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSiguiente.setForeground(new java.awt.Color(235, 237, 255));
        jbSiguiente.setText("Siguiente");
        jbSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(jbSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBodyLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanelBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanelFull.add(jPanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFull, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBuscarCiudadDestinoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscarCiudadDestinoFocusGained
        textBorderFocusGained((JTextField) evt.getComponent());
    }//GEN-LAST:event_jtfBuscarCiudadDestinoFocusGained

    private void jtfBuscarProvinciaDestinoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscarProvinciaDestinoFocusGained
        textBorderFocusGained((JTextField) evt.getComponent());
    }//GEN-LAST:event_jtfBuscarProvinciaDestinoFocusGained

    private void jtfBuscarPaisDestinoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscarPaisDestinoFocusGained
        textBorderFocusGained((JTextField) evt.getComponent());
    }//GEN-LAST:event_jtfBuscarPaisDestinoFocusGained

    private void jtfBuscarCiudadDestinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscarCiudadDestinoFocusLost
        textBorderFocusLost((JTextField) evt.getComponent());
    }//GEN-LAST:event_jtfBuscarCiudadDestinoFocusLost

    private void jtfBuscarProvinciaDestinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscarProvinciaDestinoFocusLost
        textBorderFocusLost((JTextField) evt.getComponent());
    }//GEN-LAST:event_jtfBuscarProvinciaDestinoFocusLost

    private void jtfBuscarPaisDestinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscarPaisDestinoFocusLost
        textBorderFocusLost((JTextField) evt.getComponent());
    }//GEN-LAST:event_jtfBuscarPaisDestinoFocusLost

    private void jtfBuscarCiudadDestinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarCiudadDestinoKeyReleased
        actualizarTabla("Destino");
    }//GEN-LAST:event_jtfBuscarCiudadDestinoKeyReleased

    private void jtfBuscarProvinciaDestinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarProvinciaDestinoKeyReleased
        actualizarTabla("Destino");
    }//GEN-LAST:event_jtfBuscarProvinciaDestinoKeyReleased

    private void jtfBuscarPaisDestinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarPaisDestinoKeyReleased
        actualizarTabla("Destino");
    }//GEN-LAST:event_jtfBuscarPaisDestinoKeyReleased

    private void jtfBuscarCiudadDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarCiudadDestinoKeyTyped
        KeyPress(evt, "letra");
    }//GEN-LAST:event_jtfBuscarCiudadDestinoKeyTyped

    private void jtfBuscarProvinciaDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarProvinciaDestinoKeyTyped
        KeyPress(evt, "letra");
    }//GEN-LAST:event_jtfBuscarProvinciaDestinoKeyTyped

    private void jtfBuscarPaisDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarPaisDestinoKeyTyped
        KeyPress(evt, "letra");
    }//GEN-LAST:event_jtfBuscarPaisDestinoKeyTyped

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        InvocarJInternalFrame(new ABMCiudad());
    }//GEN-LAST:event_btnSalirMousePressed

    private void jtfBuscarProvinciaOrigenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscarProvinciaOrigenFocusGained
        textBorderFocusGained((JTextField) evt.getComponent());
    }//GEN-LAST:event_jtfBuscarProvinciaOrigenFocusGained

    private void jtfBuscarProvinciaOrigenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscarProvinciaOrigenFocusLost
        textBorderFocusLost((JTextField) evt.getComponent());
    }//GEN-LAST:event_jtfBuscarProvinciaOrigenFocusLost

    private void jtfBuscarProvinciaOrigenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarProvinciaOrigenKeyReleased
        actualizarTabla("Origen");
    }//GEN-LAST:event_jtfBuscarProvinciaOrigenKeyReleased

    private void jtfBuscarProvinciaOrigenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarProvinciaOrigenKeyTyped
        KeyPress(evt, "letra");
    }//GEN-LAST:event_jtfBuscarProvinciaOrigenKeyTyped

    private void jtfBuscarPaisOrigenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscarPaisOrigenFocusGained
        textBorderFocusGained((JTextField) evt.getComponent());
    }//GEN-LAST:event_jtfBuscarPaisOrigenFocusGained

    private void jtfBuscarPaisOrigenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscarPaisOrigenFocusLost
        textBorderFocusLost((JTextField) evt.getComponent());
    }//GEN-LAST:event_jtfBuscarPaisOrigenFocusLost

    private void jtfBuscarPaisOrigenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarPaisOrigenKeyReleased
        actualizarTabla("Origen");
    }//GEN-LAST:event_jtfBuscarPaisOrigenKeyReleased

    private void jtfBuscarPaisOrigenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarPaisOrigenKeyTyped
        KeyPress(evt, "letra");
    }//GEN-LAST:event_jtfBuscarPaisOrigenKeyTyped

    private void jtfBuscarCiudadOrigenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscarCiudadOrigenFocusGained
        textBorderFocusGained((JTextField) evt.getComponent());
    }//GEN-LAST:event_jtfBuscarCiudadOrigenFocusGained

    private void jtfBuscarCiudadOrigenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscarCiudadOrigenFocusLost
        textBorderFocusLost((JTextField) evt.getComponent());
    }//GEN-LAST:event_jtfBuscarCiudadOrigenFocusLost

    private void jtfBuscarCiudadOrigenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarCiudadOrigenKeyReleased
        actualizarTabla("Origen");
    }//GEN-LAST:event_jtfBuscarCiudadOrigenKeyReleased

    private void jtfBuscarCiudadOrigenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarCiudadOrigenKeyTyped
        KeyPress(evt, "letra");
    }//GEN-LAST:event_jtfBuscarCiudadOrigenKeyTyped

    private void jbSeleccionarOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeleccionarOrigenActionPerformed
        SeleccionOrigen();
        botonFocusSeiguiente();
    }//GEN-LAST:event_jbSeleccionarOrigenActionPerformed

    private void jbSeleccionarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeleccionarDestinoActionPerformed
        SeleccionDestino();
        botonFocusSeiguiente();
    }//GEN-LAST:event_jbSeleccionarDestinoActionPerformed

    private void jbSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSiguienteActionPerformed

    private void CrearTabla() {
        //tabla origen
        JTableHeader TblHeaderOrigen = jTableOrigen.getTableHeader();
        TblHeaderOrigen.setBackground(new Color(56, 63, 79));
        TblHeaderOrigen.setForeground(new Color(235, 237, 255));

        jScrollPane1.getViewport().setBackground(new Color(56, 63, 79)); //fondo sin grilla de color
        modeloOrigen.addColumn("ID");
        modeloOrigen.addColumn("Nombre");
        modeloOrigen.addColumn("Provincia");
        modeloOrigen.addColumn("Pais");

        jTableOrigen.setModel(modeloOrigen);
        jTableOrigen.setEnabled(true);
        jTableOrigen.setRowSelectionAllowed(true);

        //Tabla destino
        JTableHeader TblHeaderDestino = jTableDestino.getTableHeader();
        TblHeaderDestino.setBackground(new Color(56, 63, 79));
        TblHeaderDestino.setForeground(new Color(235, 237, 255));

        jScrollPane2.getViewport().setBackground(new Color(56, 63, 79)); //fondo sin grilla de color
        modeloDestino.addColumn("ID");
        modeloDestino.addColumn("Nombre");
        modeloDestino.addColumn("Provincia");
        modeloDestino.addColumn("Pais");

        jTableDestino.setModel(modeloDestino);
        jTableDestino.setEnabled(true);
        jTableDestino.setRowSelectionAllowed(true);
    }

    private void textBorderFocusGained(JTextField textField) {
        textField.setBorder(new LineBorder(new Color(83, 81, 251), 3));
    }

    private void textBorderFocusLost(JTextField textField) {
        textField.setBorder(new LineBorder(new Color(235, 237, 255), 1));
    }

    private void ActualizarDatosTablaOrigen() {

        if (ciudadData.listarCiudades() != null) {
            for (Ciudad ciudad : ciudadData.listarCiudades()) {
                if (ciudad.getNombre().toUpperCase().startsWith(jtfBuscarCiudadOrigen.getText().toUpperCase())) {
                    if (ciudad.getProvincia().toUpperCase().startsWith(jtfBuscarProvinciaOrigen.getText().toUpperCase())) {
                        if (ciudad.getPais().toUpperCase().startsWith(jtfBuscarPaisOrigen.getText().toUpperCase())) {
                            modeloOrigen.addRow(new Object[]{ciudad.getIdCiudad(), ciudad.getNombre(), ciudad.getProvincia(), ciudad.getPais()});
                        }
                    }
                }
            }
        } else {
            System.out.println("No hay datos en el array");
        }
    }

    private void ActualizarDatosTablaDestino() {
        if (ciudadData.listarCiudades() != null) {
            for (Ciudad ciudad : ciudadData.listarCiudades()) {
                if (ciudad.getNombre().toUpperCase().startsWith(jtfBuscarCiudadDestino.getText().toUpperCase())) {
                    if (ciudad.getProvincia().toUpperCase().startsWith(jtfBuscarProvinciaDestino.getText().toUpperCase())) {
                        if (ciudad.getPais().toUpperCase().startsWith(jtfBuscarPaisDestino.getText().toUpperCase())) {
                            modeloDestino.addRow(new Object[]{ciudad.getIdCiudad(), ciudad.getNombre(), ciudad.getProvincia(), ciudad.getPais()});
                        }
                    }
                }
            }
        } else {
            System.out.println("No hay datos en el array");
        }
    }

    private void borrarFilaDestino() {
        int f = jTableDestino.getRowCount() - 1;
        for (; f >= 0; f--) {
            modeloDestino.removeRow(f);
        }
    }

    private void borrarFilaOrigen() {
        int f = jTableOrigen.getRowCount() - 1;
        for (; f >= 0; f--) {
            modeloOrigen.removeRow(f);
        }
    }

    private void actualizarTabla(String OrigenDestino) {
        if (OrigenDestino.equalsIgnoreCase("Origen")) {
            borrarFilaOrigen();
            ActualizarDatosTablaOrigen();
        }
        if (OrigenDestino.equalsIgnoreCase("Destino")) {
            borrarFilaDestino();
            ActualizarDatosTablaDestino();
        }

    }

    private void KeyPress(java.awt.event.KeyEvent evt, String Opcion) {
        if (Opcion.equalsIgnoreCase("letra")) {
            char c = evt.getKeyChar();
            if (Character.isDigit(c)) {
                evt.consume(); // Consume el evento si el carácter no es un número
            }
        }
        if (Opcion.equalsIgnoreCase("numero")) {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c)) {
                evt.consume(); // Consume el evento si el carácter no es un número
            }
        }

    }

    private void InvocarJInternalFrame(JInternalFrame frame) {
        BasicInternalFrameUI ui = (BasicInternalFrameUI) frame.getUI();
        ui.setNorthPane(null);
        frame.setBorder(null); // Elimina el borde
        frame.setClosable(false); // Desactiva la opción de cerrar
        frame.setIconifiable(false); // Desactiva la opción de minimizar
        frame.setOpaque(true); // Hace que el contenido sea opaco
        frame.setSize(Menu.Escritorio.getSize()); // Establece el tamaño igual al del desktopPane
        frame.setVisible(true); // Lo hace visible
        Menu.Escritorio.add(frame); // Agrega el JInternalFrame al JDesktopPane
        frame.toFront();
    }

    private void SeleccionOrigen() {
        int filas = jTableOrigen.getSelectedRow();
        if (filas != -1) {
            Color colorEditable;
            Boolean flag;
            if (jbSeleccionarOrigen.getText().equalsIgnoreCase("Seleccionar")) {
                colorEditable = new Color(66, 66, 66);
                flag = false;
                jbSeleccionarOrigen.setText("De-Seleccionar");

                jtfBuscarCiudadOrigen.setText((String) jTableOrigen.getValueAt(filas, 1));
                jtfBuscarProvinciaOrigen.setText((String) jTableOrigen.getValueAt(filas, 2));
                jtfBuscarPaisOrigen.setText((String) jTableOrigen.getValueAt(filas, 3));
            } else {
                colorEditable = new Color(56, 63, 79);
                flag = true;
                jbSeleccionarOrigen.setText("Seleccionar");

                jtfBuscarCiudadOrigen.setText("");
                jtfBuscarProvinciaOrigen.setText("");
                jtfBuscarPaisOrigen.setText("");
            }

            jTableOrigen.setFocusable(flag);
            jTableOrigen.setRowSelectionAllowed(flag);

            jtfBuscarCiudadOrigen.setEditable(flag);
            jtfBuscarCiudadOrigen.setFocusable(flag);
            jtfBuscarCiudadOrigen.setBackground(colorEditable);

            jtfBuscarProvinciaOrigen.setEditable(flag);
            jtfBuscarProvinciaOrigen.setFocusable(flag);
            jtfBuscarProvinciaOrigen.setBackground(colorEditable);

            jtfBuscarPaisOrigen.setEditable(flag);
            jtfBuscarPaisOrigen.setFocusable(flag);
            jtfBuscarPaisOrigen.setBackground(colorEditable);

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        }
    }

    private void SeleccionDestino() {
        int filas = jTableDestino.getSelectedRow();
        if (filas != -1) {
            Color colorEditable;
            Boolean flag;
            if (jbSeleccionarDestino.getText().equalsIgnoreCase("Seleccionar")) {
                colorEditable = new Color(66, 66, 66);
                flag = false;
                jbSeleccionarDestino.setText("De-Seleccionar");

                jtfBuscarCiudadDestino.setText((String) jTableDestino.getValueAt(filas, 1));
                jtfBuscarProvinciaDestino.setText((String) jTableDestino.getValueAt(filas, 2));
                jtfBuscarPaisDestino.setText((String) jTableDestino.getValueAt(filas, 3));
            } else {
                colorEditable = new Color(56, 63, 79);
                flag = true;
                jbSeleccionarDestino.setText("Seleccionar");

                jtfBuscarCiudadDestino.setText("");
                jtfBuscarProvinciaDestino.setText("");
                jtfBuscarPaisDestino.setText("");
            }

            jTableDestino.setFocusable(flag);
            jTableDestino.setRowSelectionAllowed(flag);

            jtfBuscarCiudadDestino.setEditable(flag);
            jtfBuscarCiudadDestino.setFocusable(flag);
            jtfBuscarCiudadDestino.setBackground(colorEditable);

            jtfBuscarProvinciaDestino.setEditable(flag);
            jtfBuscarProvinciaDestino.setFocusable(flag);
            jtfBuscarProvinciaDestino.setBackground(colorEditable);

            jtfBuscarPaisDestino.setEditable(flag);
            jtfBuscarPaisDestino.setFocusable(flag);
            jtfBuscarPaisDestino.setBackground(colorEditable);

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        }
    }

    private void botonFocusSeiguiente() {
        if (jbSeleccionarDestino.getText().equalsIgnoreCase("De-Seleccionar")
                && jbSeleccionarOrigen.getText().equalsIgnoreCase("De-Seleccionar")) {
            jbSiguiente.setFocusable(true);
            jbSiguiente.setEnabled(true);
            jbSiguiente.setBackground(new Color(56, 63, 79));

        } else {
            jbSiguiente.setFocusable(false);
            jbSiguiente.setEnabled(false);
                jbSiguiente.setBackground(new Color(66, 66, 66));
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelBuscar1;
    private javax.swing.JPanel jPanelFull;
    private javax.swing.JPanel jPanelHead;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTableDestino;
    private javax.swing.JTable jTableOrigen;
    private javax.swing.JButton jbSeleccionarDestino;
    private javax.swing.JButton jbSeleccionarOrigen;
    private javax.swing.JButton jbSiguiente;
    private javax.swing.JLabel jlabel_exit;
    private javax.swing.JTextField jtfBuscarCiudadDestino;
    private javax.swing.JTextField jtfBuscarCiudadOrigen;
    private javax.swing.JTextField jtfBuscarPaisDestino;
    private javax.swing.JTextField jtfBuscarPaisOrigen;
    private javax.swing.JTextField jtfBuscarProvinciaDestino;
    private javax.swing.JTextField jtfBuscarProvinciaOrigen;
    // End of variables declaration//GEN-END:variables
}
